services:
  web:
    container_name: bac_calculator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - .:/app
    restart: always
