apiVersion: apps/v1
kind: Deployment
metadata:
  name: bac-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bac-calculator
  template:
    metadata:
      labels:
        app: bac-calculator
    spec:
      containers:
        - name: bac-calculator
          image: stevomc/bac-calculator:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
          livenessProbe:
            httpGet:
              path: /health-check
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 30
      restartPolicy: Always
