apiVersion: apps/v1
kind: Deployment
metadata:
  name: bac-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bac-calculator
  template:
    metadata:
      labels:
        app: bac-calculator
    spec:
      containers:
        - name: bac-calculator
          image: stevomc/bac_calculator:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health-check
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 30
      restartPolicy: Always
